### ISSUE TITLE
Case Issues.

### ISSUE THREAD

**Issue by ellisgl** [dronecz/ESP32-Reflow-Controller#1]
A couple issues with the STLs:
C+ Case is too small:
Board: L ~105.1 mm x W ~50.9 mm
Case internally: L ~101.6 mm x W ~53.85
Also the buttons seem to be a little bit too big. Holes ~4.6 Buttons: ~4.6. Also the base of the buttons ended up touching one another.

**Comment by ellisgl** [comment]
Any update?

**Comment by dronecz** [comment]
Hi, sorry for no response. I did update [here](https://github.com/dronecz/ESP32-Reflow-Controller/commit/5c8115160fbe543e19d66ff70a04c8ddd5bfef16) and buttons should be pretty ok, It really depends on your printer resolution. Did you tried to print them in like 90% of its scale? Also they should not touch each other. I had no such issue with that and it is also look good in CAD. 
![image](https://user-images.githubusercontent.com/16454728/102687484-ae2b6200-41ef-11eb-8438-367881fdb791.png)
