### ISSUE TITLE
error: redeclaration of 'HTTP_DELETE'

### ISSUE THREAD

**Issue by nbg3000** [dronecz/ESP32-Reflow-Controller#3]
I'm working on the bootstrap+Wifi manager branch and getting some errors about redeclaration of some HTTP methods:

- HTTP_DELETE
- HTTP_METHOD_MAP
- HTTP_GET
- HTTP_HEAD

I think the problem is the use of the libraries `WiFiManager` and `ESPAsyncWebServer`. They both define this methods.

What versions of the libraries are you using?
Do i have to make changes in the libraries?

**Comment by dronecz** [comment]
You have to use WiFiManager from [this](https://github.com/tzapu/WiFiManager/tree/feature_asyncwebserver) branch. To be clear, this branch is/was just a test. FW has to be heavily modified to make it work with LVGL. 

What are you trying to achieve or are you just playing?
